name: send mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "hello world"
    
    -name: sending a mail
     if: ${{ always() }} 
     uses: devellany/send-mailer@v1.0.2
     with:
        host: smtp.google.com
        port: 465
        account: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        sender: devellany
        from: ${{secrets.EMAIL_USERNAME}}
        to: kesavan211@gmail.com,nandhini,shanmugam06@gmail.com
        subject: Test mail title.
        body: Welcom to Github Workflows.                    
          
          