name: send mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World
      run: echo "hello world"
    
    - name: sending a mail
      if: ${{ always() }} 
      uses: Kesavan211/send-mailer@v1.0.2
      with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}

          subject: Test mail title.
          body: Welcom to Github Workflows.   
          from: ${{secrets.EMAIL_USERNAME}}
          to: kesavan211@gmail.com,nandhini,shanmugam06@gmail.com
                           
          
          